<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>i_v0.5.0_v-icon notranslate mdi mdi-account-circle-outline theme--light</name>
   <tag></tag>
   <elementGuidId>de1e5b72-8072-4396-9f04-a87dc21a2c6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/header/div/a[2]/span/i</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>i.v-icon.notranslate.mdi.mdi-account-circle-outline.theme--light</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
      <webElementGuid>b6d8a2e7-8aca-41c1-97a0-816ef684b50d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>fde78a5f-2b11-412f-83b6-5e02131e8b94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>v-icon notranslate mdi mdi-account-circle-outline theme--light</value>
      <webElementGuid>453e3e0a-9699-4319-9dc7-c524d688779f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;v-application--wrap&quot;]/header[@class=&quot;my-header print-hide v-sheet v-sheet--outlined theme--light v-toolbar v-toolbar--dense v-toolbar--flat v-app-bar v-app-bar--fixed&quot;]/div[@class=&quot;v-toolbar__content&quot;]/a[@class=&quot;v-btn v-btn--icon v-btn--round v-btn--router theme--light v-size--small primary--text&quot;]/span[@class=&quot;v-btn__content&quot;]/i[@class=&quot;v-icon notranslate mdi mdi-account-circle-outline theme--light&quot;]</value>
      <webElementGuid>a0dc0069-b26c-474d-b76c-178e67829812</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/header/div/a[2]/span/i</value>
      <webElementGuid>c0544e1b-6158-4443-acf8-59222f77d2ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/span/i</value>
      <webElementGuid>6155e162-98a1-4385-9228-6b584ae065ee</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
